<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CartiScanateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('carti_scanate')->insert([
            [
                'user_id' => 1,
                'titlu' => 'Un satelit al școlii ardelene - Ștefan P. Niagoe',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 24,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Războiul pentru întregirea naționala în expresii memorabile - Aurel Neculai',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 125,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Structura socială și etnică a familiei nerejene - Dumitru V. Niculescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 54,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ținutul jertfei - I.M. Dimitrescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 25,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ștefan-Vodă și vrâncenii - No. 2 - Simion Hârnea-Năruja',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Soveja - Al. Russo',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 50,
            ],
            [
                'user_id' => 1,
                'titlu' => 'România în războiul european - Liga culturală secția Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 24,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Vrancea. poema istorica - George Christinescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Bătălia dela Mărășești - Cassian R. Munteanu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 28,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Colegiul unic și exproprierea - 1913',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Expunerea situațiunei județului Putna pe anul 1925',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Manual de Istoria Literaturii Latine - 1915 - I. Iordănescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 99,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Învățământul primar din județul Putna - Petre Iosif',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Monografia comunei rurale Nănesci - Dumitru Galian',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Moara C. T. Tatovici - 1924',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Regulamentul Societăței „Unirea” - 1879',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 7,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Situațiunea scolară a elevelor pe anul 1894 - 95',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Fițuica din carte',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 7,
            ],
            [
                'user_id' => 1,
                'titlu' => 'In fața măgurii - I. M. Dimitrescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 32,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Păstoritul în Vrancea - Ion Diaconu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 33,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Preoții în trecutul Vrancei - Simion Hârnea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 17,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista Liceului „Unirea” din Focșani - 1901',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista Liceului „Unirea” din Focșani - 1900',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 37,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Pagini răzlețe I',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 18,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Pagini răzlețe II',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 38,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Monografia regiunei Odobesti din punct de vedere viticol - Dodun des Perrieres',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 17,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani, 1901 - septembrie I',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 3,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani, 1901 - septembrie II',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani pe anul 1900',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 3,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani, anul 1900, octombrie',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 36,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani, 1901',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 35,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Revista liceului Unirea din Focșani, 1900 - septembrie III',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 29,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Misiunea statului în raport cu initiațiva privată',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 62,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Aspecte ale solidarității slave - Virgiliu P. Arbore',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 36,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Darea de Seamă pe 1937 - 1938',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 11,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Darea de Seamă despre Administrațiunea comunei Focsani - Th. M. Bassarabianu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Darea de Seamă pe 1910 - 1911',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 12,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Darea de Seamă pe anul 1909 - 1910',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul ligei culturale - secția Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 13,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Stihuri populare culese de I. M. Dimitrescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 11,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Școlile rurale din județul Putna - N. N. Saveanu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Aerul lichid pe înțelesul tuturor - G. G. Longinescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 67,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului Unirea din Focșani pe anul 1924 - 1925',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 48,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului Unirea din Focșani pe anul 1923 - 1924',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 46,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului Unirea din Focșani pe anul 1908 - 1909',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul Școalei Profesionale de Fete Gr. I - 1922 - 1923',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul Școalei Secundare de fete, 1921 - 1923',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 37,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului de fete pe anii 1930 - 1934',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 61,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului Unirea din Focșani pe anul 1922 - 1923',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 82,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului de fete pe anii 1923 - 1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 88,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului de fete pe anii 1925 - 1926',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 73,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului de fete pe anii 1921- 1922, 1929 - 1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul liceului de fete pe anii 1908 - 1909',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1936',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1933',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 78,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1932',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 75,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1931',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 45,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Mărășeștii în vechi cărți poștale ilustrate: 1900-1939',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 107,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Mărășești în fapte și imagini',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 318,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Mărăști… ecouri în timp…',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 285,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cărțile eroilor și ale războiului',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia 1856',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 29,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Mărășești - Oituz',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 96,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoricul bisericei Sfântului Gheorghe din cimitirul sudic, Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ion Ionescu dela Brad',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 13,
            ],
            [
                'user_id' => 1,
                'titlu' => 'În Vrancea cu Mihail Sadoveanu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 7,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Închinare liceului Unirea 1916',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 103,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Doi ani de activitate',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Memorie Locală - Fond documentar',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 115,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Alimentarea cu apă a orașiului Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuar liceu Unirea 1921-1922',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuar liceu Unirea 1923-1924',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 90,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuar liceu Unirea 1924-1925',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 92,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuar liceu Unirea 1930-1936',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 112,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul școalei profesionale de fete gr I',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 36,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul școalei secundare de fete',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Expunerea situațiunei județului Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Expunerea situațiunei județului Râmnicul Sărat',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 151,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Fărămituri ianuarie 1926',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 94,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Frământări didactice an XVIII nr 1234',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 44,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Frământări didactice an VIII nr 9-10',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 90,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Frământări didactice an XIII nr 5-6',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 84,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Geografia județului Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Impozitul pe lux și cifra de afaceri',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 180,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Monografia comunei rurale Nănesci',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 38,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Noul metod de geografie elementară',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 53,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Opera lui Anghel Saligny',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 30,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Siluete Focșănene',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Statutele bibliotecei publice',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Un satelit al școalei Ardelene',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 26,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul pe anii 1923-1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 93,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul 1908-1909',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 42,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul 1925-1926',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 138,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul 1927-1928',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 38,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Calendarul Băncei „Economia din Focșani”',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 63,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoricul Presei Focșănene (bibliografie 1859-1900)',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 16,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Oficial al primariei urbei Focsani, no.1-58',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 270,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Camerei de Comerț 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 12,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Camerei de Comerț 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 9,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Camerei de Comerț și Industrie An 42,1-8,1932',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Camerei de Comerț și Industrie An 42,9-12,1932',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Starea Economică a Țarei și convențiile,1902',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 31,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Note critice și bibliografice - Ion Diaconu - 1943',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Folklor din Rîmnicul-sărat I,1933',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 130,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Folklor din Rîmnicul-sărat II, 1934',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 200,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Banca Putnei Darea de seamă a Consiliului de administrație și Raportul Censorilor',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 18,
            ],
            [
                'user_id' => 1,
                'titlu' => 'În Fața Măgurii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 62,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Însemnări cu privire la orașul Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 84,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Jertfă și Biruință - I.M. Dimitrecu - 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 144,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Note Critice și bibliografice',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 38,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Oameni dela Oraș',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 94,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Orientări etnografice I',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 30,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Orientări folklorice I',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 26,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Orientări folklorice II',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 26,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Orientări folklorice III',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Poesia populară de militărie în războiul nostru din 1941',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 28,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Psihologie Și Creație Populară',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 24,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Răvașele biruitorilor',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'SKRISORI DIN ȚARA ȚÎNȚĂREASKĂ ȘI POEZII NOUE',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 130,
            ],
            [
                'user_id' => 1,
                'titlu' => 'SUR LE TREMBLEMENT DE TERRE DU 29 JUILLET 1942…DES MONTAGNES DE VRANCEA',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ținutul Jertfei',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 46,
            ],
            [
                'user_id' => 1,
                'titlu' => 'VIAEAȚ și OPERILE LUI DE Clement Bontea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 41,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul II al Gimnaziului General Averescu Din Adjud',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 48,
            ],
            [
                'user_id' => 1,
                'titlu' => 'ANUARUL pe anul1922-1923',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 155,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Aspecte ale solidarității slave',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 57,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul camerei de comerciu no.5, 6 și 7',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul camerei de comerciu Nr.20 și 21',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul camerei de comerciu Nr.26-27',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 25,
            ],
            [
                'user_id' => 1,
                'titlu' => 'BULETINUL Camerei de comerciu și industrie - nr. 24-25',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 29,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul camerei de comerciu și industrie nr.22',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Caracterul etnografic al Dobrogei sudice',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 48,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Pagini răzlete din vieata politico-culturală a vecinilor nostri slavi nr.935',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 78,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul scoalei normale pr carol 1921_1925',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 92,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Biblia și Știința',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 54,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Bolta bizantina',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 110,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul Camerei de Comerț și Industrie ian dec 1937',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 90,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci Bacău sectiunea Focșani ian dec 1934',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci Focșani ian august 1933',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci Focșani sep dec 1933',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 66,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Colegiul unic și exproprierea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 65,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Contesa de Noailles',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoricul bisericii Sf Gheorghe din cimitirul sudic',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 28,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Note critice și bibliografie Ion Diaconu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Sensuri și aspecte la Ioan Creanga',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Virgil Huzum Zenit',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 24,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul pe anii 1930 -1934',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul 1926-1928 Lic Unirea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 137,
            ],
            [
                'user_id' => 1,
                'titlu' => 'O fată singură',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 246,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul pe anul 1922-1923 lucrat de directorul liceului Al. Georgiadi',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 155,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anuarul Societății Literare',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 173,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 49,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Boale și leacuri, Ediția a II-a, 1942',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 168,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cartea Sănătăței',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 70,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Documente putnene, II, Vrancea Irești-Câmpuri, Aurel V. Sava, 1931',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 310,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ethnos Revistă de grai, studiu și creație romînească, Ion Diaconu, Focșani, anul II 1942-1942',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 436,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Foklor din Rîmnicul-sărat,III, 1948, Ion Diaconu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 210,
            ],
            [
                'user_id' => 1,
                'titlu' => 'În fața Măgurii. Din ciclul „Oameni dela oraș”, 1934, I. M. Dimitrescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 62,
            ],
            [
                'user_id' => 1,
                'titlu' => 'La Radio București-15 cuvântări rostite de G.G. Longinescu, București, 1932',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 268,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Monografia județului Putna, Focșani, 1943',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 157,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ținutul jertfei (Județul Putna de ieri și de azi), 1938, I.M. Dimitrescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 48,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Titu Maiorescu, cu un portret din tinerețe, Soveja, Editura „Cartea Romanească”',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 150,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Trei comedii complecte, Composiții și prelucrări, Artistul Lupescu, Focșani, 1890',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 66,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Budgetul Comunei Focșani Pe anul Financiar 1900-1901',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Clasicismul ca bază a învățământului. Învățământul științiific al limbilor',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Datinile și obiceiurile noastre de la Sărbătorile Paștelor, Nr.5, 1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'DIN CAMPANIE Focșani-Corabia-Etropole',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 42,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Din viața lui Maiorescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Extracte și metode de prepararea lor, Ioan Huzum farmacist',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 76,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Făt -Frumos Horia Furtună',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 71,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Învățământul Primar din Județul Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 24,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Partidele Politice Și Statul Corporativ',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 18,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Povestea Vrancei, Nr.1',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 19,
            ],
            [
                'user_id' => 1,
                'titlu' => 'QU EST-CE QUE LA TRANSYLVANIE',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 59,
            ],
            [
                'user_id' => 1,
                'titlu' => 'ȘCOALA POPORULUI Patru cuvântări S. Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 49,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Țara Vrancei, Nr.3-4, 1930',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Altă creștere Simion Mehedinți ediția III',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 356,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci circumscriptia VII Focșani ian 1924',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 44,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci circuscriptia VII a Focșani 1927 feb mar',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 76,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul cci Focșani 1937 ian dec',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 90,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul colegiului medicilor din județul Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul ligei culturale secția Focșani mai 1916',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de putna 1 noi 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 1 oct 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 10 noi 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 10 oct 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 20 ian 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 20 iulie 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 20 martie 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 16,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna 20 oct 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 8,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol de Putna anul III nr 3 martie 1921',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 16,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletinul sindicatului viticol Putna Focșani 20 sept 1919',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 16,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Buletiul cci circumscriptia VII Focșani oct_dec 1922',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 20,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ce trebuie sa cugete un român',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 54,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Din pribegie',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 164,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Documente istorice mănăstiri',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 252,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Extracte și metode de preparare a lor',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 150,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Flăcarile amorului Grigorie Josescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 120,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Horia Furtună Făt Frumos',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 140,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Închinare liceului Unirea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 106,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoria literaturii latine',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 190,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Manual de antichități romane',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 166,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Poezii I.G.Milcovu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 92,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Simion Mehedinți opere complete vol 1 geographica partea a doua',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 344,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Simion Mehedinți opere complete vol 1 Introducere in geografie',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 284,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Țara vrancei Simion Harnea',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'D.C. OLĂNESCU',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 66,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cântece și Lacrimi',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 35,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Starea podgorenilor din județul Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 21,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Les Panorpides de la collection du Musee Grigore Antipa - Bucarest',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 7,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Legea pentru apărarea viticulturii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 9,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Munca În Lumina Sfintei Scripturi',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 33,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Privire asupra Județului Putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 45,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Oameni de la Munte',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 131,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Către noua Generație 1912, S. Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 101,
            ],
            [
                'user_id' => 1,
                'titlu' => 'MIJN ROEMEENS HART IN BELGIE',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 27,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Vremelnicii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 34,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Necesitatea Frumuseții',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 43,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Din viața marilor apicultori',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 29,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoricul Mănăstirei” Vărzărești” și al comunei Urechești',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 47,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Doftorii sătești',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 15,
            ],
            [
                'user_id' => 1,
                'titlu' => 'PERLE ȘI COMORI',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 67,
            ],
            [
                'user_id' => 1,
                'titlu' => 'STATUTE Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 9,
            ],
            [
                'user_id' => 1,
                'titlu' => 'PAJIȘTILE SUFLETULUI',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 23,
            ],
            [
                'user_id' => 1,
                'titlu' => 'REZZO sau LUPTA ÎNTRE IDEAL ȘI REAL',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'NELINIȘTI poeme',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => '32 de opere din literatura română - alte opere din literatura română - I.M.Rascu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 480,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Alte opere din literatura română - I.M.Rascu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 226,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cincinat Pavelescu poezii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 228,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Convingeri literare I.M.Rascu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 204,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cum se dezorganizează învățământul',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 92,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Dimitrie C. Ollănescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 126,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Istoricul scoalei primare de băieți nr 2 din Focșani',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 120,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Pagini alese din scriitori români',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 471,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Regulament pentru înființarea impozitelor și taxelor comunale',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 108,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Altă creștere - Simion Mehedinți - ediția V',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 360,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Anale politice - Simion Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 222,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Ce trebuie să cugete un român despre țara și nația română',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 52,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cele cinci continente - Simion Mehedinți - fără încheiere',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 228,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Dumitru Constantin Ollănescu - Teatru',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 274,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Geografia economică - S. Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 116,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Introducere în studiul geografiei - Simion Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 109,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Le pays et le peuple roumain - Simion Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 150,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Le pays et le peuple roumain',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 146,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Libertate Marin Simionescu Rîmniceanu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 132,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Neliniști I.M.Rascu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Oameni de la munte ediția 1920',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 219,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Oameni de la munte',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 259,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Politica de vorbe și omul politic',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 240,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Poporul - Simion Mehedinți',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 186,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Primăvara literară',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 260,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Primăvara literară',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 260,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Aerul lichid',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 132,
            ],
            [
                'user_id' => 1,
                'titlu' => 'La Troita',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 35,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Chimie și mineralogie - partea 1',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 490,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Chimie și mineralogie - partea 2',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 38,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Pe cărările științei',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 180,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Lege asupra drepturilor proprietarilor',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 56,
            ],
            [
                'user_id' => 1,
                'titlu' => 'L’ ASSOCIATION MOLCULAIRE, son passé, son présent, son avenir',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 64,
            ],
            [
                'user_id' => 1,
                'titlu' => 'PETRE LICIU - Conferința ținută în Focșani de Alexandru Lascarov',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 36,
            ],
            [
                'user_id' => 1,
                'titlu' => 'TRAIASCA NATURA - Chimia de azi și totdeauna la noi și pretutindeni, G.G. Longinescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 12,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Camille Matignon',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 22,
            ],
            [
                'user_id' => 1,
                'titlu' => 'De vorba cu strop de apa',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 163,
            ],
            [
                'user_id' => 1,
                'titlu' => 'La Radio București',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 263,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Lecția de deschidere a cursului de drept român',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 23,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Legea pentru apărarea viticulturii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 12,
            ],
            [
                'user_id' => 1,
                'titlu' => 'amintiri si medalioane literare i m rascu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 196,
            ],
            [
                'user_id' => 1,
                'titlu' => 'buget focsani pe exercitiul 1935_1936',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 100,
            ],
            [
                'user_id' => 1,
                'titlu' => 'la sezatoare',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 40,
            ],
            [
                'user_id' => 1,
                'titlu' => 'manual de antichitati romane',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 164,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia anul I vol 1',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 120,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia anul I vol 2',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 128,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia anul II vol 1',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 207,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Milcovia anul III vol 1_2',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 144,
            ],
            [
                'user_id' => 1,
                'titlu' => 'milcovia anul IV vol 1_2',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 148,
            ],
            [
                'user_id' => 1,
                'titlu' => 'misiunea statului in raport cu initiativa privata',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 52,
            ],
            [
                'user_id' => 1,
                'titlu' => 'moara_c_t_tatovici_1924',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 18,
            ],
            [
                'user_id' => 1,
                'titlu' => 'ollanescu ascanio_poesii',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 224,
            ],
            [
                'user_id' => 1,
                'titlu' => 'patrimoniul public si starea economica a judetului putna',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 200,
            ],
            [
                'user_id' => 1,
                'titlu' => 'regulament infiintare impozite si taxe comunale',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'revista liceului unirea focsani noiembrie 1900',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'revista liceului unirea focsani octombrie 1900',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 68,
            ],
            [
                'user_id' => 1,
                'titlu' => 'traditie si actualitate romineasca',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 104,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Lege asupra drepturilor proprietarilor - G. I. Demetriu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 56,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cronici științifice - G. G. Longinescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 186,
            ],
            [
                'user_id' => 1,
                'titlu' => 'Cronici științifice - volumul III - G. G. Longinescu',
                'autor' => '',
                'editura' => '',
                'anul' => '',
                'nr_pagini' => 186,
            ],
        ]);
    }
}
